import { initializeApp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import { getFirestore, collection, addDoc, getDocs, query, orderBy, serverTimestamp, doc, updateDoc, deleteDoc, getDoc, setDoc } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import { getStorage, ref, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-storage.js";
import { firebaseConfig, ADMIN_USERNAME, ADMIN_EMAIL } from "./config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),storage=getStorage(app);const $=id=>document.getElementById(id);let products=[],categories=[];
const adminEmail=ADMIN_EMAIL;
function esc(v=""){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function money(v){return `৳ ${Number(v||0).toLocaleString('en-BD')}`}
function isAdmin(user){return !!user&&user.email===adminEmail}
function showTab(name){document.querySelectorAll('.tab-page').forEach(x=>x.hidden=x.id!==name);document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));if(name==='products')loadProducts();if(name==='categories')loadCategories();if(name==='orders')loadOrders();if(name==='settings')loadSettings()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>showTab(b.dataset.jump));
$('loginBtn').onclick=async()=>{const u=$('loginUser').value.trim(),p=$('loginPass').value;if(u!==ADMIN_USERNAME){$('loginMsg').textContent='Username সঠিক নয়।';return}try{await signInWithEmailAndPassword(auth,adminEmail,p);$('loginMsg').textContent=''}catch(e){$('loginMsg').textContent='Login failed: '+e.message}};
$('logoutBtn').onclick=()=>signOut(auth);onAuthStateChanged(auth,u=>{if(isAdmin(u)){$('loginView').hidden=true;$('appView').hidden=false;$('adminEmail').textContent=u.email;showTab('dashboard');loadDashboard()}else{$('loginView').hidden=false;$('appView').hidden=true;if(u)signOut(auth)}});
async function loadDashboard(){try{const ps=await getDocs(collection(db,'products')),os=await getDocs(collection(db,'orders'));let pending=0,total=0;os.forEach(d=>{const x=d.data();if((x.status||'Pending')==='Pending')pending++;total+=Number(x.total||0)});$('statProducts').textContent=ps.size;$('statOrders').textContent=os.size;$('statPending').textContent=pending;$('statSales').textContent=money(total)}catch(e){console.error(e)}}
async function loadCategories(){try{const snap=await getDocs(query(collection(db,'categories'),orderBy('name')));categories=snap.docs.map(d=>({id:d.id,...d.data()}));if(!categories.length){for(const n of ['ইলেকট্রনিক্স','মোবাইল ও গ্যাজেট','ফ্যাশন','মেয়েদের ফ্যাশন','ছেলেদের ফ্যাশন','ঘড়ি','গ্রোসারি','হোম ও লাইফস্টাইল','বিউটি','স্পোর্টস','অটোমোটিভ','অন্যান্য'])await addDoc(collection(db,'categories'),{name:n,createdAt:serverTimestamp()});const s=await getDocs(query(collection(db,'categories'),orderBy('name')));categories=s.docs.map(d=>({id:d.id,...d.data()}))}renderCategories();fillCategorySelect()}catch(e){$('catList').textContent='Categories load failed: '+e.message}}
function renderCategories(){$('catList').innerHTML=categories.map(c=>`<div class="cat-item"><b>${esc(c.name)}</b><button class="mini danger" data-del-cat="${c.id}">Delete</button></div>`).join('');document.querySelectorAll('[data-del-cat]').forEach(b=>b.onclick=async()=>{if(!confirm('Category delete করবেন?'))return;await deleteDoc(doc(db,'categories',b.dataset.delCat));loadCategories()})}
function fillCategorySelect(){$('pCategory').innerHTML=categories.map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join('')}
$('catForm').onsubmit=async e=>{e.preventDefault();const name=$('catName').value.trim();if(!name)return;await addDoc(collection(db,'categories'),{name,createdAt:serverTimestamp()});$('catName').value='';loadCategories()};
async function loadProducts(){try{const snap=await getDocs(query(collection(db,'products'),orderBy('createdAt','desc')));products=snap.docs.map(d=>({id:d.id,...d.data()}));renderProducts(products);if(!categories.length)await loadCategories()}catch(e){$('productTable').textContent='Products load failed: '+e.message}}
function renderProducts(rows){$('productTable').innerHTML=`<table class="table"><thead><tr><th>Image</th><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Actions</th></tr></thead><tbody>${rows.map(p=>`<tr><td><img class="thumb" src="${esc(p.img||'logo.png')}" onerror="this.src='logo.png'"></td><td><b>${esc(p.title)}</b><br><small>${esc(p.description||'')}</small></td><td>${esc(p.category||'')}</td><td>${money(p.price)}</td><td>${esc(p.stock??0)}</td><td><div class="table-actions"><button class="mini secondary" data-edit="${p.id}">Edit</button><button class="mini danger" data-del="${p.id}">Delete</button></div></td></tr>`).join('')}</tbody></table>`;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProduct(products.find(p=>p.id===b.dataset.edit)));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(!confirm('এই product delete করবেন?'))return;await deleteDoc(doc(db,'products',b.dataset.del));loadProducts();loadDashboard()})}
$('productSearch').oninput=()=>{const q=$('productSearch').value.toLowerCase();renderProducts(products.filter(p=>`${p.title} ${p.category}`.toLowerCase().includes(q)))};
function editProduct(p){$('productId').value=p.id;$('pTitle').value=p.title||'';$('pCategory').value=p.category||categories[0]?.name||'';$('pPrice').value=p.price||'';$('pOldPrice').value=p.oldPrice||'';$('pStock').value=p.stock??0;$('pRating').value=p.rating||5;$('pImageUrl').value=p.img||'';$('pDescription').value=p.description||'';window.scrollTo({top:0,behavior:'smooth'})}
$('newProductBtn').onclick=()=>clearForm();$('cancelProduct').onclick=()=>clearForm();function clearForm(){document.getElementById('productForm').reset();$('productId').value='';$('pRating').value=5;$('pStock').value=0}
async function uploadImage(file){if(!file)return '';const safe=file.name.replace(/[^a-z0-9.\-_]/gi,'_');const r=ref(storage,`products/${Date.now()}-${safe}`);await uploadBytes(r,file);return getDownloadURL(r)}
$('productForm').onsubmit=async e=>{e.preventDefault();const btn=$('saveProductBtn');btn.disabled=true;$('productMsg').textContent='Saving...';try{let img=$('pImageUrl').value.trim();if($('pImageFile').files[0])img=await uploadImage($('pImageFile').files[0]);if(!img)img='logo.png';const data={title:$('pTitle').value.trim(),category:$('pCategory').value,price:Number($('pPrice').value),oldPrice:Number($('pOldPrice').value||0),stock:Number($('pStock').value||0),rating:Number($('pRating').value||5),img,description:$('pDescription').value.trim(),updatedAt:serverTimestamp()};const id=$('productId').value;if(id)await updateDoc(doc(db,'products',id),data);else await addDoc(collection(db,'products'),{...data,createdAt:serverTimestamp()});$('productMsg').textContent='Product saved successfully.';clearForm();await loadProducts();await loadDashboard()}catch(e){$('productMsg').textContent='Error: '+e.message}finally{btn.disabled=false}};
async function loadOrders(){try{const snap=await getDocs(query(collection(db,'orders'),orderBy('createdAt','desc')));const rows=snap.docs.map(d=>({id:d.id,...d.data()}));$('orderTable').innerHTML=rows.length?`<table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th>Update</th></tr></thead><tbody>${rows.map(o=>`<tr><td><b>#${esc(o.id.slice(-7))}</b><br><small>${esc(o.items?.[0]?.title||'')}</small></td><td>${esc(o.customerName||'')}<br>${esc(o.customerPhone||'')}<br><small>${esc(o.customerAddress||'')}</small></td><td>${money(o.total)}</td><td>${esc(o.paymentMethod||'Cash on Delivery')}</td><td>${esc(o.status||'Pending')}</td><td><select class="order-status" data-order="${o.id}"><option ${o.status==='Pending'?'selected':''}>Pending</option><option ${o.status==='Confirmed'?'selected':''}>Confirmed</option><option ${o.status==='Processing'?'selected':''}>Processing</option><option ${o.status==='Shipped'?'selected':''}>Shipped</option><option ${o.status==='Delivered'?'selected':''}>Delivered</option><option ${o.status==='Cancelled'?'selected':''}>Cancelled</option></select></td></tr>`).join('')}</tbody></table>`:'কোনো order নেই।';document.querySelectorAll('[data-order]').forEach(s=>s.onchange=async()=>{await updateDoc(doc(db,'orders',s.dataset.order),{status:s.value,updatedAt:serverTimestamp()});loadDashboard()})}catch(e){$('orderTable').textContent='Orders load failed: '+e.message}}
$('refreshOrders').onclick=loadOrders;
async function loadSettings(){const snap=await getDoc(doc(db,'settings','home'));if(snap.exists()){const s=snap.data();$('sTitle').value=s.title||'';$('sSubtitle').value=s.subtitle||'';$('sBanner').value=s.banner||''}}
$('settingsForm').onsubmit=async e=>{e.preventDefault();await setDoc(doc(db,'settings','home'),{title:$('sTitle').value,subtitle:$('sSubtitle').value,banner:$('sBanner').value,updatedAt:serverTimestamp()});$('settingsMsg').textContent='Saved.'};
