import { initializeApp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import { getFirestore, collection, query, orderBy, limit, getDocs, addDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import { firebaseConfig } from "./config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();
const $=id=>document.getElementById(id);const grid=$("productGrid"),loading=$("loading"),search=$("searchInput");
let allProducts=[],filtered=[],activeCategory="All",selected=null,lastIndex=0,loggedUser=null;const PAGE=12;
const fallbackCats=["ইলেকট্রনিক্স","মোবাইল ও গ্যাজেট","ফ্যাশন","মেয়েদের ফ্যাশন","ছেলেদের ফ্যাশন","ঘড়ি","গ্রোসারি","হোম ও লাইফস্টাইল","বিউটি","স্পোর্টস","অটোমোটিভ","অন্যান্য"];
function esc(v=""){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function money(v){return `৳ ${Number(v||0).toLocaleString('en-BD')}`}
function renderCategories(){const names=["সব পণ্য",...new Set(allProducts.map(p=>p.category).filter(Boolean)),...fallbackCats];const unique=[...new Set(names)];$("categoryList").innerHTML=unique.map(c=>`<button class="${(c==="সব পণ্য"?activeCategory==="All":activeCategory===c)?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');$("chips").innerHTML=unique.slice(0,10).map(c=>`<button class="${(c==="সব পণ্য"?activeCategory==="All":activeCategory===c)?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat==='সব পণ্য'?'All':b.dataset.cat;renderCategories();applyFilters();document.getElementById('products')?.scrollIntoView({behavior:'smooth'})})}
function showSkeleton(){grid.innerHTML=Array.from({length:10},()=>'<div class="skeleton"></div>').join('')}
function renderProducts(reset=true){if(reset){grid.innerHTML="";lastIndex=0}const slice=filtered.slice(lastIndex,lastIndex+PAGE);lastIndex+=slice.length;slice.forEach(p=>{const old=Number(p.oldPrice||0),price=Number(p.price||0),discount=old>price?Math.round((old-price)/old*100):0;const el=document.createElement('article');el.className='product';el.innerHTML=`<img class="product-img" src="${esc(p.img||'logo.png')}" alt="${esc(p.title||'Product')}" loading="lazy" decoding="async" onerror="this.src='logo.png'"><div class="product-content"><div class="product-title">${esc(p.title||'পণ্য')}</div><div><span class="price">${money(price)}</span>${old>price?`<span class="old">${money(old)}</span><span class="discount">-${discount}%</span>`:''}</div><div class="rating">★★★★★ ${esc(p.rating||'5.0')}</div></div>`;el.onclick=()=>openProduct(p);grid.appendChild(el)});$("resultCount").textContent=`${filtered.length}টি পণ্য`;loading.style.display=lastIndex<filtered.length?'block':'none'}
function applyFilters(){const q=search.value.trim().toLowerCase();filtered=allProducts.filter(p=>(activeCategory==='All'||p.category===activeCategory)&&(!q||`${p.title||''} ${p.category||''} ${p.brand||''}`.toLowerCase().includes(q)));renderProducts(true)}
async function loadProducts(){showSkeleton();try{const snap=await getDocs(query(collection(db,'products'),orderBy('createdAt','desc'),limit(100)));allProducts=snap.docs.map(d=>({id:d.id,...d.data()}));renderCategories();applyFilters();if(!allProducts.length){grid.innerHTML='<div style="grid-column:1/-1;background:#fff;padding:45px;text-align:center;border-radius:10px">এখনও কোনো পণ্য যোগ করা হয়নি। Admin Panel থেকে প্রথম পণ্যটি যোগ করুন।</div>';loading.style.display='none'}}catch(e){console.error(e);grid.innerHTML='<div style="grid-column:1/-1;background:#fff;padding:45px;text-align:center">Firebase সংযোগ বা Firestore Rules পরীক্ষা করুন।</div>';loading.style.display='none'}}
function openProduct(p){selected=p;$("modalImg").src=p.img||'logo.png';$("modalTitle").textContent=p.title||'পণ্য';$("modalCategory").textContent=p.category||'Product';$("modalPrice").textContent=money(p.price);$("modalOldPrice").textContent=p.oldPrice?money(p.oldPrice):'';$("modalDescription").textContent=p.description||'Cash on Delivery available.';showModal('productModal')}
function showModal(id){$(id).hidden=false;document.body.style.overflow='hidden'}function closeModal(id){$(id).hidden=true;document.body.style.overflow=''}document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModal(m.id)});
function cart(){try{return JSON.parse(localStorage.getItem('kinza-cart')||'[]')}catch{return[]}}function saveCart(c){localStorage.setItem('kinza-cart',JSON.stringify(c));$("cartCount").textContent=c.reduce((n,x)=>n+(x.qty||1),0);$("mobileCartCount").textContent=c.reduce((n,x)=>n+(x.qty||1),0)}
function addToCart(){if(!selected)return;const c=cart(),found=c.find(x=>x.id===selected.id);if(found)found.qty=(found.qty||1)+1;else c.push({id:selected.id,title:selected.title,price:selected.price,img:selected.img,qty:1});saveCart(c);closeModal('productModal');openCart()}
function openCart(){const c=cart();$("cartBody").innerHTML=c.length?c.map((x,i)=>`<div class="cart-row"><img src="${esc(x.img||'logo.png')}" alt=""><div><b>${esc(x.title)}</b><div>${money(x.price)} × ${x.qty||1}</div></div><button class="secondary" data-remove="${i}">×</button></div>`).join('')+`<div style="padding:15px 0;font-weight:800">মোট: ${money(c.reduce((n,x)=>n+Number(x.price||0)*(x.qty||1),0))}</div><button class="primary" id="cartCheckout">Checkout</button>`:'<p>আপনার কার্ট খালি।</p>';$('cartBody').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const cc=cart();cc.splice(Number(b.dataset.remove),1);saveCart(cc);openCart()});$('cartCheckout')?.addEventListener('click',()=>{if(!loggedUser){closeModal('cartModal');openAccount();return}const cc=cart();if(cc[0]){selected=cc[0];closeModal('cartModal');openCheckout()}});showModal('cartModal')}
async function login(){try{await signInWithPopup(auth,provider)}catch(e){alert(e.code==='auth/unauthorized-domain'?'Firebase Console → Authentication → Authorized domains-এ আপনার domain যোগ করুন।':'লগইন করা যায়নি।')}}
function accountUI(){if(!loggedUser){$("accountBody").innerHTML='<h2>Kinza Shop</h2><p>অর্ডার করতে Google দিয়ে সাইন ইন করুন।</p><button class="primary" id="loginNow">Google দিয়ে সাইন ইন</button>';$('loginNow').onclick=login}else{$("accountBody").innerHTML=`<h2>স্বাগতম, ${esc(loggedUser.displayName||'Customer')}</h2><p>${esc(loggedUser.email||'')}</p><button class="secondary" id="ordersNow">আমার অর্ডার</button> <button class="primary" id="logoutNow">লগআউট</button>`;$('loginNow')?.remove();$('ordersNow').onclick=openMyOrders;$('logoutNow').onclick=()=>signOut(auth)}}
function openAccount(){accountUI();showModal('accountModal')}$('accountBtn').onclick=openAccount;$('bottomAccount').onclick=openAccount;$('cartBtn').onclick=openCart;$('mobileCart').onclick=openCart;$('mobileCategories').onclick=()=>window.scrollTo({top:260,behavior:'smooth'});$('shopNow').onclick=()=>document.getElementById('products').scrollIntoView({behavior:'smooth'});
function openCheckout(){if(!selected)return;if(!loggedUser){closeModal('productModal');openAccount();return}$('checkoutSummary').innerHTML=`<b>${esc(selected.title)}</b><br>${money(selected.price)}<br><small>Cash on Delivery</small>`;$('custName').value=loggedUser.displayName||'';showModal('checkoutModal')}
$('addCart').onclick=addToCart;$('buyNow').onclick=openCheckout;$('orderForm').onsubmit=async e=>{e.preventDefault();if(!loggedUser||!selected)return;const btn=$('confirmOrder');btn.disabled=true;btn.textContent='অর্ডার হচ্ছে...';try{const qty=1;await addDoc(collection(db,'orders'),{items:[{productId:selected.id,title:selected.title,price:Number(selected.price||0),qty}],total:Number(selected.price||0),customerName:$('custName').value.trim(),customerPhone:$('custPhone').value.trim(),customerAddress:$('custAddress').value.trim(),paymentMethod:'Cash on Delivery',customerEmail:loggedUser.email||'',userUid:loggedUser.uid,status:'Pending',createdAt:serverTimestamp()});alert('অর্ডার সফলভাবে জমা হয়েছে!');localStorage.removeItem('kinza-cart');saveCart([]);closeModal('checkoutModal');e.target.reset()}catch(err){alert('অর্ডার করা যায়নি: '+err.message)}finally{btn.disabled=false;btn.textContent='অর্ডার কনফার্ম করুন'}};
async function openMyOrders(){if(!loggedUser)return;showModal('ordersModal');$('myOrders').innerHTML='লোড হচ্ছে...';try{const snap=await getDocs(query(collection(db,'orders'),orderBy('createdAt','desc'),limit(50)));const rows=snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.userUid===loggedUser.uid);$('myOrders').innerHTML=rows.length?rows.map(o=>`<div class="order-card"><b>${esc(o.items?.[0]?.title||'Order')}</b><br>${money(o.total)}<br><span class="status">${esc(o.status||'Pending')}</span><br><small>${esc(o.customerAddress||'')}</small></div>`).join(''):'কোনো অর্ডার পাওয়া যায়নি।'}catch(e){$('myOrders').textContent='অর্ডার লোড করা যায়নি।'}}
$('searchBtn').onclick=applyFilters;search.oninput=()=>{clearTimeout(window.__search);window.__search=setTimeout(applyFilters,100)};search.onkeydown=e=>{if(e.key==='Enter')applyFilters()};
const sentinel=$('loadMoreSentinel');new IntersectionObserver(es=>{if(es[0].isIntersecting&&lastIndex<filtered.length)renderProducts(false)},{rootMargin:'500px'}).observe(sentinel);saveCart(cart());onAuthStateChanged(auth,u=>{loggedUser=u;$('accountText').textContent=u?'আমার অ্যাকাউন্ট':'অ্যাকাউন্ট'});loadProducts();
